/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prueba.h"

int *
suma_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a + argp->b;

    printf("Sumando %i + %i = %i\n", argp->a,argp->b,result);

	return &result;
}

int *
multiplicacion_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a * argp->b;

    printf("Multiplicando %i x %i\n = %i\n", argp->a,argp->b,result);


	return &result;
}

int *
resta_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a - argp->b;

    printf("Restando %i - %i\n = %i\n", argp->a,argp->b,result);


	return &result;
}

int *
division_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a/argp->b;

    printf("Dividiendo %i / %i\n = %i\n", argp->a,argp->b,result);


	/*
	 * insert server code here
	 */

	return &result;
}
